# Generated by Django 4.2.14 on 2024-07-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=100, unique=True)),
                ('date_received', models.DateField()),
                ('received_from', models.CharField(max_length=100)),
                ('type_of_document', models.CharField(max_length=100)),
                ('subjects', models.TextField()),
                ('forwarded_to', models.CharField(max_length=100)),
                ('date_transmitted', models.DateField()),
                ('received_by', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('reference_no', models.CharField(max_length=100)),
                ('encoded_by', models.CharField(max_length=100)),
            ],
        ),
    ]
