# Generated by Django 4.2.14 on 2024-08-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_outgoing_delete_outgoingdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='outadinvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=100)),
                ('received_from', models.CharField(max_length=100)),
                ('subjects', models.TextField()),
                ('forwarded_to', models.CharField(max_length=100)),
                ('date_transmitted', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
