# Generated by Django 4.2.14 on 2024-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_mailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIForApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('received_from', models.CharField(max_length=255)),
                ('subjects', models.TextField()),
                ('field_office', models.CharField(max_length=255)),
                ('forwarded_to', models.CharField(max_length=255)),
                ('date_transmitted', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('return_result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
