# Generated by Django 4.2.14 on 2024-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_biforapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biforapplicant',
            name='field_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biforapplicant',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biforapplicant',
            name='return_result',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biforapplicant',
            name='subjects',
            field=models.CharField(max_length=255),
        ),
    ]
