# Generated by Django 4.2.14 on 2024-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_biforapplicant_field_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('ro_do', models.CharField(max_length=255)),
                ('date_received', models.DateField()),
                ('date_transmitted', models.DateField(blank=True, null=True)),
                ('transmitted_to', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
