# Generated by Django 4.2.14 on 2024-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_finalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='tracking_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
