# Generated by Django 4.2.14 on 2024-08-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_finalreport_tracking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalreport',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
