# Generated by Django 4.2.14 on 2024-08-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_coplan_noticeofoperation_operate_postoperationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biforapplicant',
            name='subjects',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coplan',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noticeofoperation',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='operate',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postoperationreport',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
