# Generated by Django 4.2.14 on 2024-08-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_biforapplicant_subjects_alter_coplan_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoperationreport',
            name='approve_amount',
        ),
        migrations.RemoveField(
            model_name='postoperationreport',
            name='estimated_exp',
        ),
        migrations.AddField(
            model_name='postoperationreport',
            name='disposition_result',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
