# Generated by Django 4.2.14 on 2024-08-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_remove_postoperationreport_approve_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeofoperation',
            name='approve_amount',
        ),
        migrations.RemoveField(
            model_name='noticeofoperation',
            name='estimated_exp',
        ),
        migrations.AlterField(
            model_name='noticeofoperation',
            name='adinvs_rs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticeofoperation',
            name='complainant',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
