# Generated by Django 4.2.14 on 2024-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_authoritytooperate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoplanStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=500)),
                ('month', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
