# Generated by Django 4.2.14 on 2024-08-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_alter_document_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_transmitted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
