# Generated by Django 4.2.14 on 2024-08-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_document_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_received',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='encoded_by',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='received_by',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='received_from',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='reference_no',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='remarks',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='subjects',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
