# Generated by Django 4.2.14 on 2024-08-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_alter_document_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_received',
            field=models.DateField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_transmitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
